### ISSUE TITLE
Running

### ISSUE THREAD

**Issue by hdfsyu** [CarsonKompon/pico-night-punkin#1]
I tried to run it but on PICO-8 I got this cartridge error (I got the cart file from releases): FUTURE_VERSION: 30 FUTURE_VERSION: 30 COULD NOT LOAD help pls

**Comment by CarsonKompon** [comment]
Make sure you're on PICO-8 version **0.2.2c**
This is the most up-to-date version of PICO-8 at the moment, and was the version that these carts were made in :)

**Comment by hdfsyu** [comment]
XD im dumb OK gotta update my pico-8 version SEE YA!
