### ISSUE TITLE
Whats the embedded code?

### ISSUE THREAD

**Issue by robloxDevGuy** [CarsonKompon/pico-night-punkin#2]
I want to make this on google sites but i dont know how to get the embedded code from all those files into one. Can you put the embedded code in description or something

**Comment by CarsonKompon** [comment]
You can find embed code on the lexaloffle [forum post ](https://www.lexaloffle.com/bbs/?tid=42715) underneath the main cart

```html
<iframe src="https://www.lexaloffle.com/bbs/widget.php?pid=fnf_menu" allowfullscreen width="621" height="513" style="border:none; overflow:hidden"></iframe>
```
